# Matrix Math Refresher, with Numpy

In [1]:
import numpy as np

# Dimensionality of data

Data can come in many different shapes and sizes. For example, a scalar value such as a persons *height*, a vector of scalars such as a list of *height, weight and age*, a matrix consisting of rows and columns, such as a *grayscale image*.

A scalar is *zero dimensional*
A vector is *one dimensional*
A matrix is *two dimensional*

Beyond this, we refer to the data structure as a *tensor*, which can be any dimensional, but is generally *greater than two dimensional*. For example, a colour image would be structured as a *three dimensional tensor*

In numpy, tensors are generally represented in `ndarray` objects. These can be of any dimension, and so we can represent all of our data in these objects. However, note that every object in an `ndarray` **MUST** be of the same type.

In [3]:
# A scalar in numpy:
s = np.array(5)
s.shape

()

Note that the shape of the defined scalar returns `()`, as the scalar value is zero dimensional.

Vectors are also easy to define; simply input a python list:

In [6]:
# A vector in numpy:
v = np.array([1,2,3])
v.shape

(3,)

Matrices are a bit less intuitive, and must be input as a *list of lists*. Each list represents one row of the matrix, and they must all be the same length.

In [7]:
# A matrix in numpy:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m.shape

(3, 3)

You can create a tensor of any shape using the `np.array()` constructor and passing in a combination of python lists

## Element-wise Operations
It is often much faster to perform scalar *element-wise* operations on a matrix, rather than manually writing a loop to apply an operation to each value in turn. Thankfully, this is made very easy with numpy.

Without numpy:

In [10]:
values = np.array([1,2,3,4,5])

In [11]:
%%time
for i in range(len(values)):
    values[i] += 5

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 13.4 µs


With numpy:

In [12]:
%%time
values += 5

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 21.9 µs


Note that numpy automatically performs element-wise manipulation of the tensors.

Numpy can also easily handle element-wise operations between two tensors, so long as they have compatible shapes.

In [13]:
m = np.array([[1,2],[3,4]])
m *= m
display(m)

array([[ 1,  4],
       [ 9, 16]])

In [18]:
m2 = np.array([[3,4],[1,2]])
res = m + m2
display(res)

array([[ 4,  8],
       [10, 18]])

In [19]:
m3 = np.array([[1,2,3],[4,5,6]])
display(m + m3)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

Note that the two arrays of different sizes cannot be summed element-wise as there is no mapping between the values in the different indices.

Note as well that trying to multiply these two tensors also results in the same error. These two objects can be *matrix multiplied*, but the default scalar multiplication doesn't work because of the difference in shapes of the tensors

In [22]:
m * m3

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [23]:
# To matrix multiply:
res = np.matmul(m, m3)
display(res)

array([[ 17,  22,  27],
       [ 73,  98, 123]])

In [24]:
# Getting the transpose:
res.T

array([[ 17,  73],
       [ 22,  98],
       [ 27, 123]])

In [26]:
np.min(res)

17

In [27]:
m.shape[0]

2